services:
  frontend:
    image: diegoalvarez1/15dias-frontend:latest
    container_name: 15dias-frontend
    ports:
      - "5173:4173"
    environment:
      VITE_API_URL: https://solemne2.onrender.com/api