name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Vitest
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Game

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # PRIMERO NODE
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # DESPUÉS PNPM
      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Ejecutar tests
        run: pnpm test

      - name: Subir reporte de cobertura
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Game/coverage/
          retention-days: 7
